### ISSUE TITLE
Issues running parse

### ISSUE THREAD

**Issue by ryanrussell** [rossf7/elasticrawl#10]
Hi, Trying to run ubuntu 14.04 and can't get through the parse step on the github readme.

Any ideas as to the source of the issue?

Thanks!
Ryan

root@etl-local:/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64# ./elasticrawl parse CC-MAIN-2014-49 --max-segments 2 --max-files 3
Segments
Segment: 1416400372202.67 Files: 150
Segment: 1416400372490.23 Files: 124

Job configuration
Crawl: CC-MAIN-2014-49 Segments: 2 Parsing: 3 files per segment

Cluster configuration
Master: 1 m1.medium  (Spot: 0.12)
Core:   2 m1.medium  (Spot: 0.12)
Task:   --
Launch job? (y/n)
y
 ERROR: Elasticrawl::ElasticMapReduceAccessError
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/job.rb:52:in `rescue in run_job_flow'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/job.rb:48:in`run_job_flow'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/parse_job.rb:22:in `run'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:65:in`parse'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:134:in `<top (required)>'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in`load'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `<main>'
/home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:146:in`rescue in <top (required)>': undefined method `status' for "InstanceProfile is required for creating cluster":String (NoMethodError)
    from /home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:133:in`<top (required)>'
    from /home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `load'
    from /home/ubuntu/workspace/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in`<main>'

**Comment by tomas-hanzlik** [comment]
Someone who figured out how to solve this problem?

Thanks!

**Comment by rossf7** [comment]
Really sorry that this has fallen off my radar. I'll try and take a look at the weekend.

**Comment by benmccann** [comment]
I'm getting this error as well. Here's the stack trace in an easier to read format:

```
ERROR: Elasticrawl::ElasticMapReduceAccessError
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/job.rb:52:in `rescue in run_job_flow'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/job.rb:48:in `run_job_flow'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/lib/elasticrawl/parse_job.rb:22:in `run'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:65:in `parse'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:134:in `<top (required)>'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `load'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `<main>'
/src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:146:in `rescue in <top (required)>': undefined method `status' for "InstanceProfile is required for creating cluster":String (NoMethodError)
    from /src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/gems/elasticrawl-1.1.3/bin/elasticrawl:133:in `<top (required)>'
    from /src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `load'
    from /src/elasticrawl-1.1.3-linux-x86_64/lib/vendor/ruby/2.1.0/bin/elasticrawl:23:in `<main>'
```

**Comment by benmccann** [comment]
I'm pretty new to Ruby, but I tried running `rake` and it seems most of the tests are failing:

>72 examples, 38 failures

**Comment by benmccann** [comment]
Looks like every test failure is the same:

      TypeError:
        can't cast URI::Generic to string
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/quoting.rb:34:in `rescue in type_cast'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/quoting.rb:23:in `type_cast'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:290:in `block in exec_query'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:289:in `map'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:289:in `exec_query'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:127:in `first'
      # /home/bmccann/.rvm/gems/ruby-2.1.4/gems/activerecord-4.2.3/lib/active_record/relation.rb:155:in `first_or_create'
      # ./lib/elasticrawl/crawl_segment.rb:20:in `create_segment'

**Comment by benmccann** [comment]
Here are [the docs for "InstanceProfile"](http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-usingrole-instanceprofile.html)

**Comment by rossf7** [comment]
@benmccann I've released v1.1.4 of the deploy packages and pushed the change to RubyGems. It's working for me but please could you retest to make sure it fixes the issue?

**Comment by benmccann** [comment]
awesome. thanks so much for the quick release

**Comment by rossf7** [comment]
Cleaning up issues and noticed I'd forgotten to close this.
