### ISSUE TITLE
Bad segments using latest CommonCrawl path

### ISSUE THREAD

**Issue by laxatives** [rossf7/elasticrawl#21]
Looks like elasticrawl thinks it is a directory above where it actually is since the s3 path change. This used to show segments like `1448398462665.97` and `1448398462686.42` now has a single segment, `warc`.

For example, 

```
> elasticrawl parse CC-MAIN-2015-48 --max-segments 2 --max-files 2
Segments
Segment: warc Files: 35700

Job configuration
Crawl: CC-MAIN-2015-48 Segments: 1 Parsing: 2 files per segment
```

**Comment by laxatives** [comment]
Maybe this should be a separate issue, but would it be straightforward to use a newer AMI with support for Java 8? Or is there a way to configure the instances to use Java 8?

**Comment by samhumeau** [comment]
Not tested yet but l.131 of crawl.rb seems to be the culprit:
`segment_name = warc_path.split('/')[4]` 
may not be valid anymore since the segment paths have lost a slash due to the location change. 
(I don't know Ruby and its tools at all, it may take a while for me to test that hypothesis)

**Comment by samhumeau** [comment]
Made a pull request, switching from "[4]" to "[3]" did the trick

**Comment by rossf7** [comment]
Thanks for reporting this and for the PR. I've just pushed v1.1.7 of the Gem that should work with the new S3 location for the Common Crawl data.

Laxatives,
on the AMI I think it has to be one supported by EMR. You should be able to change this in the cluster.yml but its not something I've tried. Please do raise another issue if this doesn't work.

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/ami-versions-supported.html
